/**
 * Patterns Registry
 *
 * Centralized export of all regex patterns used in entity recognition.
 */

// PHP Patterns
export {
    PHP_PATTERNS,
    RELATION_PATTERNS,
    CLASS_DECLARATION,
    NAMESPACE,
    MODEL_EXTENDS,
    MODEL_TABLE,
    MODEL_FILLABLE,
    MODEL_CASTS,
    BELONGS_TO,
    HAS_MANY,
    HAS_ONE,
    BELONGS_TO_MANY,
    MORPH_TO,
    MORPH_MANY,
    CONTROLLER_EXTENDS,
    CONTROLLER_METHOD,
    MIDDLEWARE,
    FORM_REQUEST_EXTENDS,
    RULES_METHOD,
    SERVICE_CLASS,
} from './php-patterns.js';

// Vue Patterns
export {
    VUE_PATTERNS,
    INERTIA_PATTERNS,
    SCRIPT_SETUP,
    SCRIPT_SECTION,
    DEFINE_PROPS_TS,
    DEFINE_PROPS_INTERFACE,
    DEFINE_PROPS_OBJ,
    WITH_DEFAULTS,
    DEFINE_EMITS_TS,
    DEFINE_EMITS_ARR,
    IMPORT_STATEMENT,
    COMPOSABLE_IMPORT,
    INERTIA_LINK,
    INERTIA_USE_PAGE,
    INERTIA_USE_FORM,
    INERTIA_ROUTER,
    USES_INERTIA,
    COMPONENT_OPTIONS,
    DEFINE_COMPONENT,
    LIFECYCLE_HOOK,
    VUE_USE_COMPOSABLE,
    TEMPLATE_SECTION,
    SLOT_USAGE,
    COMPONENT_USAGE,
} from './vue-patterns.js';
