import * as fs from 'fs';
import * as path from 'path';
// @ts-ignore
import { debugSystem, DEBUG_CATEGORIES } from '../../../../root/mcp/node-terminal/mcp/DebugSystem.cjs';

export class DocumentManager {
    private projectRoot: string;
    private feedbackPath: string;
    private reportsPath: string;
    private rulesPath: string;
    private guidesPath: string;
    private pluginName: string;
    private pluginVersion: string;

    constructor(projectRoot: string, feedbackPath: string, reportsPath: string, rulesPath: string, guidesPath: string, pluginName: string, pluginVersion: string) {
        this.projectRoot = projectRoot;
        this.feedbackPath = feedbackPath;
        this.reportsPath = reportsPath;
        this.rulesPath = rulesPath;
        this.guidesPath = guidesPath;
        this.pluginName = pluginName;
        this.pluginVersion = pluginVersion;
    }

    public createDocument(content: string, documentType: string, title: string, metadata: any = {}): { success: boolean, error?: string, filePath?: string, message?: string } {
        if (!content || typeof content !== 'string') {
            return {
                success: false,
                error: 'Document content must be text'
            };
        }

        let targetDir: string;
        let fileExtension: string;

        switch (documentType.toLowerCase()) {
            case 'report':
                targetDir = this.reportsPath;
                fileExtension = 'md';
                break;
            case 'rule':
            case 'rules':
                targetDir = this.rulesPath;
                fileExtension = 'md';
                break;
            case 'guide':
            case 'guides':
                targetDir = this.guidesPath;
                fileExtension = 'md';
                break;
            case 'analysis':
                targetDir = this.reportsPath;
                fileExtension = 'md';
                break;
            case 'task':
                targetDir = this.feedbackPath;
                fileExtension = 'json';
                break;
            default:
                targetDir = this.reportsPath;
                fileExtension = 'md';
        }

        try {
            fs.mkdirSync(targetDir, { recursive: true });

            const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
            const safeTitle = title.replace(/[^a-zA-Z0-9\s-]/g, '').replace(/\s+/g, '_');
            const filename = `${safeTitle}_${timestamp}.${fileExtension}`;
            const filePath = path.join(targetDir, filename);

            let fileContent: string;

            if (fileExtension === 'json') {
                const documentData = {
                    title: title,
                    type: documentType,
                    content: content,
                    metadata: {
                        ...metadata,
                        createdAt: new Date().toISOString(),
                        pluginName: this.pluginName,
                        projectPath: this.projectRoot
                    }
                };
                fileContent = JSON.stringify(documentData, null, 2);
            } else {
                fileContent = `# ${title}\n\n`;
                fileContent += `**Document Type:** ${documentType}\n`;
                fileContent += `**Created:** ${new Date().toLocaleString()}\n`;
                fileContent += `**Plugin:** ${this.pluginName}\n\n`;
                
                if (metadata.description) {
                    fileContent += `## Description\n\n${metadata.description}\n\n`;
                }
                
                if (metadata.tags && metadata.tags.length > 0) {
                    fileContent += `**Tags:** ${metadata.tags.join(', ')}\n\n`;
                }
                
                fileContent += `## Content\n\n${content}\n\n`;
                
                if (metadata.notes) {
                    fileContent += `## Notes\n\n${metadata.notes}\n\n`;
                }
                
                fileContent += `---  \n*Automatically generated by ${this.pluginName} system*`;
            }

            fs.writeFileSync(filePath, fileContent, 'utf8');

            debugSystem.registerProblem({
                category: DEBUG_CATEGORIES.DOCUMENT_GENERATION,
                title: 'Document created',
                description: `Document of type ${documentType} created: ${title}`,
                context: {
                    documentType,
                    title,
                    filePath,
                    targetDir
                }
            });

            return {
                success: true,
                filePath: filePath,
                message: `Document ${documentType} successfully created: ${filename}`
            };
        } catch (error: any) {
            debugSystem.registerProblem({
                category: DEBUG_CATEGORIES.FILE_SYSTEM_ERROR,
                title: 'Document creation error',
                description: `Failed to create document: ${error.message}`,
                errorDetails: error.message,
                context: { documentType, title, targetDir }
            });

            return {
                success: false,
                error: `Document creation error: ${error.message}`
            };
        }
    }
}
