#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

$logFile = 'storage/logs/laravel.log';

// Clear the specific log file for this test
file_put_contents($logFile, '');

// Register the Composer autoloader...
require __DIR__ . '/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$status = (require_once __DIR__ . '/bootstrap/app.php')
    ->handleCommand(new ArgvInput);

exit($status);
