/**
 * @generated Generated by scripts/generate-action-types.js
 * DO NOT EDIT MANUALLY
 * 
 * Generated at: 2026-03-03T18:14:06.357Z
 * 
 * This file contains action types for client-side usage.
 *
 * Protocol types for new-request-flow: https://github.com/org-carrier/a2a-script-agent/tree/main/docs/new-request-flow
 */


/**
 * Available action types
 */
export enum ActionType {
  AiSessionContext = 'ai-session-context',
  FixImportsGeneric = 'fix-imports-generic',
  FixVueImports = 'fix-vue-imports'
}

/**
 * Action metadata from definitions
 */
export interface ActionMetadata {
  id: string;
  version: string;
  title: string;
  description: string;
  priority: number;
  triggers: string[];
}

export const ACTIONS_METADATA: Record<ActionType, ActionMetadata> = {
  [ActionType.AiSessionContext]: {
    id: 'ai-session-context',
    version: '1.0',
    title: 'AI Session Context',
    description: 'Система для сохранения и использования контекста из предыдущих сессий при работе с новыми задачами',
    priority: 90,
    triggers: ["сохрани контекст","запомни","new session","new task context","создай сессию","контекст изучения","план изучения","ai session","ai context"]
  },
  [ActionType.FixImportsGeneric]: {
    id: 'fix-imports-generic',
    version: '1.0',
    title: 'Исправить импорты (Generic)',
    description: 'Универсальное исправление сломанных импортов в JS/TS проектах. Работает с любыми фреймворками.',
    priority: 100,
    triggers: ["fix imports","resolve imports","broken imports","fix import paths","cannot find module","module not found","исправить импорты","сломанные импорты","не найден модуль"]
  },
  [ActionType.FixVueImports]: {
    id: 'fix-vue-imports',
    version: '1',
    title: 'Исправить сломанные импорты в Vue файлах',
    description: 'Исправить сломанные импорты в Vue файлах. Автоматически определить и исправить проблемы с импортами в Vue компонентах',
    priority: 100,
    triggers: ["fix vue imports","resolve import issues","broken imports","fix import paths","исправить импорты","исправить импорты в vue","vue импорты","сломанные импорты"]
  }
} as const;

// ============================================
// Execute Action Types (Action-Key Shape)
// ============================================

export interface FormInput {
  name: string;
  type: 'text' | 'textarea' | 'select' | 'checkbox' | 'number';
  label?: string;
  required?: boolean;
  default?: unknown;
  options?: Array<{ value: unknown; label: string }>;
}

export interface FormChoice {
  id: string;
  label: string;
  value?: unknown;
  description?: string;
}

export interface FormAction {
  title?: string;
  description?: string;
  input?: FormInput[];
  choices?: FormChoice[];
}

export interface ScriptAction {
  /** Code to execute */
  code: string;
  /** Programming language */
  language?: 'javascript' | 'typescript';
  /** Sandbox type */
  sandbox?: 'vm2' | 'node';
  /** Input parameters for the script */
  input?: Record<string, unknown>;
  /** Output (optional, for streaming) */
  output?: string;
  /** Timeout in milliseconds */
  timeout?: number;
}

export interface RagSearchFilters {
  file_types?: string[];
  directories?: string[];
  framework?: string;
  exclude?: string[];
}

export interface RagSearchOptions {
  limit?: number;
  min_score?: number;
  include_context?: boolean;
  highlight_matches?: boolean;
}

export interface RagSearchAction {
  query: string;
  filters?: RagSearchFilters;
  options?: RagSearchOptions;
}

export interface RagSearchResult {
  file: string;
  score: number;
  matches: Array<{
    line_start: number;
    line_end: number;
    content: string;
    highlight: string;
    context_score: number;
  }>;
  metadata: {
    framework: string;
    type: string;
    last_modified: string;
  };
}

export interface ReadFileAction {
  path: string;
  startLine?: number;
  endLine?: number;
}

export interface WriteFileAction {
  path: string;
  content: string;
  createDirs?: boolean;
}

export interface ExecuteCommandAction {
  command: string;
  cwd?: string;
  env?: Record<string, string>;
  timeout?: number;
}

export interface ExecuteCommandResult {
  command: string;
  exitCode: number;
  stdout: string;
  stderr: string;
}

export interface MessageAction {
  content: string;
  role?: 'system' | 'user' | 'assistant';
}

// ============================================
// Execute Types (with Execute prefix - new naming convention)
// @see docs/new-request-flow/PROTOCOL.md#action-key-shape
// ============================================

/**
 * Execute script action type
 * @see docs/new-request-flow/PROTOCOL.md#script
 */
export type ExecuteScript = ScriptAction;

/**
 * Execute read-file action type
 * @see docs/new-request-flow/PROTOCOL.md#read-file
 */
export type ExecuteReadFile = ReadFileAction;

/**
 * Execute write-file action type
 * @see docs/new-request-flow/PROTOCOL.md#write-file
 */
export type ExecuteWriteFile = WriteFileAction;

/**
 * Execute RAG search action type
 * @see docs/new-request-flow/PROTOCOL.md#rag-search
 */
export type ExecuteRagSearch = RagSearchAction;

/**
 * Execute command action type
 * @see docs/new-request-flow/PROTOCOL.md#execute-command
 */
export type ExecuteCommand = ExecuteCommandAction;

/**
 * Execute form action type
 * @see docs/new-request-flow/PROTOCOL.md#form
 */
export type ExecuteForm = FormAction;

/**
 * Execute message action type
 * @see docs/new-request-flow/PROTOCOL.md#message
 */
export type ExecuteMessage = MessageAction;

/**
 * Execute payload with action-key shape
 * All execute objects MUST use this format
 * @see docs/new-request-flow/PROTOCOL.md#action-key-shape-обязательно
 */
export interface ExecutePayload {
  form?: FormAction;
  script?: ScriptAction;
  'rag-search'?: RagSearchAction;
  'read-file'?: ReadFileAction;
  'write-file'?: WriteFileAction;
  'execute-command'?: ExecuteCommandAction;
  message?: MessageAction;
}

/**
 * Action type keys
 */
export type ExecuteActionType = keyof ExecutePayload;

// ============================================
// Result Types (Action-Key Shape)
// ============================================

export interface ScriptResult {
  /** Script output */
  output?: unknown;
  /** Exit code (0 for success) */
  exitCode: number;
  /** Error message if failed */
  error?: string;
}

export interface RagSearchResultPayload {
  results: RagSearchResult[];
  files: string[];
  query?: string;
}

export interface ReadFileResult {
  path: string;
  content?: string;
  error?: string;
}

export interface WriteFileResult {
  path: string;
  success: boolean;
  error?: string;
}

export interface FormResult {
  choice?: string;
  input?: Record<string, unknown>;
}

/**
 * Result payload with action-key shape
 * @see docs/new-request-flow/PROTOCOL.md#action-key-shape
 */
export interface ActionResult {
  script?: ScriptResult;
  'rag-search'?: RagSearchResultPayload;
  'read-file'?: ReadFileResult;
  'write-file'?: WriteFileResult;
  'execute-command'?: ExecuteCommandResult;
  form?: FormResult;
  choice?: string;
  completed?: boolean;
  [key: string]: unknown;
}

// ============================================
// Result Types (with Result suffix - new naming convention)
// @see docs/new-request-flow/PROTOCOL.md#action-key-shape
// ============================================

/**
 * Script result type
 * @see docs/new-request-flow/PROTOCOL.md#script
 */
export type ScriptActionResult = ScriptResult;

/**
 * Read file result type
 * @see docs/new-request-flow/PROTOCOL.md#read-file
 */
export type ReadFileActionResult = ReadFileResult;

/**
 * Write file result type
 * @see docs/new-request-flow/PROTOCOL.md#write-file
 */
export type WriteFileActionResult = WriteFileResult;

/**
 * RAG search result type
 * @see docs/new-request-flow/PROTOCOL.md#rag-search
 */
export type RagSearchActionResult = RagSearchResultPayload;

/**
 * Execute command result type
 * @see docs/new-request-flow/PROTOCOL.md#execute-command
 */
export type CommandActionResult = ExecuteCommandResult;

/**
 * Form result type
 * @see docs/new-request-flow/PROTOCOL.md#form
 */
export type FormActionResult = FormResult;
