/**
 * @generated Generated by scripts/generate-action-types.js
 * DO NOT EDIT MANUALLY
 * 
 * Generated at: 2026-03-03T18:14:06.354Z
 * 
 * This file contains:
 * - Action definition types
 * - Execute action types (action-key shape)
 * - Zod schemas for runtime validation
 */


// ============================================
// Execute Action Types (Action-Key Shape)
// ============================================

export interface FormInput {
  name: string;
  type: 'text' | 'textarea' | 'select' | 'checkbox' | 'number';
  label?: string;
  required?: boolean;
  default?: unknown;
  options?: Array<{ value: unknown; label: string }>;
}

export interface FormChoice {
  id: string;
  label: string;
  value?: unknown;
  description?: string;
}

export interface FormAction {
  title?: string;
  description?: string;
  input?: FormInput[];
  choices?: FormChoice[];
}

export interface ScriptAction {
  input?: Record<string, unknown>;
  output?: string;
  code: string;
  timeout?: number;
}

export interface RagSearchFilters {
  file_types?: string[];
  directories?: string[];
  framework?: string;
  exclude?: string[];
}

export interface RagSearchOptions {
  limit?: number;
  min_score?: number;
  include_context?: boolean;
  highlight_matches?: boolean;
}

export interface RagSearchAction {
  query: string;
  filters?: RagSearchFilters;
  options?: RagSearchOptions;
}

export interface RagSearchResult {
  file: string;
  score: number;
  matches: Array<{
    line_start: number;
    line_end: number;
    content: string;
    highlight: string;
    context_score: number;
  }>;
  metadata: {
    framework: string;
    type: string;
    last_modified: string;
  };
}

export interface ReadFileAction {
  path: string;
  startLine?: number;
  endLine?: number;
}

export interface WriteFileAction {
  path: string;
  content: string;
  createDirs?: boolean;
}

export interface ExecuteCommandAction {
  command: string;
  cwd?: string;
  env?: Record<string, string>;
  timeout?: number;
}

export interface ExecuteCommandResult {
  command: string;
  exitCode: number;
  stdout: string;
  stderr: string;
}

export interface MessageAction {
  content: string;
  role?: 'system' | 'user' | 'assistant';
}

/**
 * Execute payload with action-key shape
 * All execute objects MUST use this format
 */
export interface ExecutePayload {
  form?: FormAction;
  script?: ScriptAction;
  'rag-search'?: RagSearchAction;
  'read-file'?: ReadFileAction;
  'write-file'?: WriteFileAction;
  'execute-command'?: ExecuteCommandAction;
  message?: MessageAction;
}

/**
 * Action type keys
 */
export type ExecuteActionType = keyof ExecutePayload;

// ============================================
// Result Types (Action-Key Shape)
// ============================================

export interface ScriptResult {
  output?: unknown;
  error?: string;
}

export interface RagSearchResultPayload {
  results: RagSearchResult[];
  files: string[];
  query?: string;
}

export interface ReadFileResult {
  path: string;
  content?: string;
  error?: string;
}

export interface WriteFileResult {
  path: string;
  success: boolean;
  error?: string;
}

export interface FormResult {
  choice?: string;
  input?: Record<string, unknown>;
}

/**
 * Result payload with action-key shape
 */
export interface ActionResult {
  script?: ScriptResult;
  'rag-search'?: RagSearchResultPayload;
  'read-file'?: ReadFileResult;
  'write-file'?: WriteFileResult;
  'execute-command'?: ExecuteCommandResult;
  form?: FormResult;
  choice?: string;
  completed?: boolean;
  [key: string]: unknown;
}

/**
 * Union of all action types
 */
export type Action =
  | AiSessionContextAction
  | FixImportsGenericAction
  | FixVueImportsAction;

/**
 * Action type discriminator
 */
export type ActionType = 'ai-session-context' | 'fix-imports-generic' | 'fix-vue-imports';

/**
 * AI Session Context
 * Система для сохранения и использования контекста из предыдущих сессий при работе с новыми задачами
 */
export interface AiSessionContextAction {
  id: 'ai-session-context';
  version: '1.0';
  title: 'AI Session Context';
  description: 'Система для сохранения и использования контекста из предыдущих сессий при работе с новыми задачами';
  priority: 90;
  triggers: string[];
  context: {
  type: 'session_context';
  creates_files: boolean;
  llm_guided: boolean;
  iterations: 'multiple';
};
  steps: ('capture-task' | 'analyze-intent' | 'collect-session-context' | 'create-learning-plan' | 'save-context-document')[];
}

export const aiSessionContextActionSchema = {
  id: 'ai-session-context',
  version: '1.0',
  triggers: ["сохрани контекст","запомни","new session","new task context","создай сессию","контекст изучения","план изучения","ai session","ai context"],
  priority: 90,
} as const;


/**
 * Исправить импорты (Generic)
 * Универсальное исправление сломанных импортов в JS/TS проектах. Работает с любыми фреймворками.
 */
export interface FixImportsGenericAction {
  id: 'fix-imports-generic';
  version: '1.0';
  title: 'Исправить импорты (Generic)';
  description: 'Универсальное исправление сломанных импортов в JS/TS проектах. Работает с любыми фреймворками.';
  priority: 100;
  triggers: string[];
  context: {
  language: 'typescript';
  supports: object;
};
  steps: ('collect-files' | 'find-imports' | 'analyze-imports' | 'generate-patches' | 'confirm-patches' | 'apply-patches' | 'generate-report')[];
}

export const fixImportsGenericActionSchema = {
  id: 'fix-imports-generic',
  version: '1.0',
  triggers: ["fix imports","resolve imports","broken imports","fix import paths","cannot find module","module not found","исправить импорты","сломанные импорты","не найден модуль"],
  priority: 100,
} as const;


/**
 * Исправить сломанные импорты в Vue файлах
 * Исправить сломанные импорты в Vue файлах. Автоматически определить и исправить проблемы с импортами в Vue компонентах
 */
export interface FixVueImportsAction {
  id: 'fix-vue-imports';
  version: '1';
  title: 'Исправить сломанные импорты в Vue файлах';
  description: 'Исправить сломанные импорты в Vue файлах. Автоматически определить и исправить проблемы с импортами в Vue компонентах';
  priority: 100;
  triggers: string[];
  context: {
  framework: 'vue';
  'build-tool': 'vite';
};
  steps: ('collect' | 'analyze' | 'detect' | 'resolve' | 'apply')[];
}

export const fixVueImportsActionSchema = {
  id: 'fix-vue-imports',
  version: '1',
  triggers: ["fix vue imports","resolve import issues","broken imports","fix import paths","исправить импорты","исправить импорты в vue","vue импорты","сломанные импорты"],
  priority: 100,
} as const;


// ============================================
// Zod Schemas for Runtime Validation
// ============================================

import { z } from 'zod';

export const FormInputSchema = z.object({
  name: z.string(),
  type: z.enum(['text', 'textarea', 'select', 'checkbox', 'number']),
  label: z.string().optional(),
  required: z.boolean().optional(),
  default: z.unknown().optional(),
  options: z.array(z.object({
    value: z.unknown(),
    label: z.string()
  })).optional()
});

export const FormChoiceSchema = z.object({
  id: z.string(),
  label: z.string(),
  value: z.unknown().optional(),
  description: z.string().optional()
});

export const FormActionSchema = z.object({
  title: z.string().optional(),
  description: z.string().optional(),
  input: z.array(FormInputSchema).optional(),
  choices: z.array(FormChoiceSchema).optional()
});

export const ScriptActionSchema = z.object({
  input: z.record(z.unknown()).optional(),
  output: z.string().optional(),
  code: z.string(),
  timeout: z.number().optional()
});

export const RagSearchFiltersSchema = z.object({
  file_types: z.array(z.string()).optional(),
  directories: z.array(z.string()).optional(),
  framework: z.string().optional(),
  exclude: z.array(z.string()).optional()
});

export const RagSearchOptionsSchema = z.object({
  limit: z.number().optional(),
  min_score: z.number().optional(),
  include_context: z.boolean().optional(),
  highlight_matches: z.boolean().optional()
});

export const RagSearchActionSchema = z.object({
  query: z.string(),
  filters: RagSearchFiltersSchema.optional(),
  options: RagSearchOptionsSchema.optional()
});

export const ReadFileActionSchema = z.object({
  path: z.string(),
  startLine: z.number().optional(),
  endLine: z.number().optional()
});

export const WriteFileActionSchema = z.object({
  path: z.string(),
  content: z.string(),
  createDirs: z.boolean().optional()
});

export const ExecuteCommandActionSchema = z.object({
  command: z.string(),
  cwd: z.string().optional(),
  env: z.record(z.string()).optional(),
  timeout: z.number().optional()
});

export const MessageActionSchema = z.object({
  content: z.string(),
  role: z.enum(['system', 'user', 'assistant']).optional()
});

export const ExecutePayloadSchema = z.object({
  form: FormActionSchema.optional(),
  script: ScriptActionSchema.optional(),
  'rag-search': RagSearchActionSchema.optional(),
  'read-file': ReadFileActionSchema.optional(),
  'write-file': WriteFileActionSchema.optional(),
  'execute-command': ExecuteCommandActionSchema.optional(),
  message: MessageActionSchema.optional()
}).strict();

export const ActionResultSchema = z.object({
  script: z.object({
    output: z.unknown().optional(),
    error: z.string().optional()
  }).optional(),
  'rag-search': z.object({
    results: z.array(z.unknown()),
    files: z.array(z.string()),
    query: z.string().optional()
  }).optional(),
  'read-file': z.object({
    path: z.string(),
    content: z.string().optional(),
    error: z.string().optional()
  }).optional(),
  'write-file': z.object({
    path: z.string(),
    success: z.boolean(),
    error: z.string().optional()
  }).optional(),
  'execute-command': z.object({
    command: z.string(),
    exitCode: z.number(),
    stdout: z.string(),
    stderr: z.string()
  }).optional(),
  form: z.object({
    choice: z.string().optional(),
    input: z.record(z.unknown()).optional()
  }).optional(),
  choice: z.string().optional(),
  completed: z.boolean().optional()
}).passthrough();

/**
 * Validate execute payload
 */
export function validateExecutePayload(payload: unknown): { success: boolean; error?: string } {
  const result = ExecutePayloadSchema.safeParse(payload);
  if (result.success) {
    return { success: true };
  }
  return { success: false, error: result.error.message };
}

/**
 * Validate action result
 */
export function validateActionResult(result: unknown): { success: boolean; error?: string } {
  const parseResult = ActionResultSchema.safeParse(result);
  if (parseResult.success) {
    return { success: true };
  }
  return { success: false, error: parseResult.error.message };
}
