#!/usr/bin/env node
import{readFileSync,writeFileSync,readdirSync,existsSync}from'fs';
import{join,basename}from'path';
function walk(d){const r=[];try{for(const e of readdirSync(d,{withFileTypes:true})){const f=join(d,e.name);if(e.isDirectory()&&e.name!=='node_modules'&&!e.name.startsWith('.'))walk(f).forEach(x=>r.push(x));else if(e.isFile()&&e.name.endsWith('.ts')&&!e.name.endsWith('.d.ts'))r.push(f);}}catch{}return r;}
const dirs=['packages/server/src','packages/transform/src','packages/services/src','packages/daemon/src','packages/actions/src','packages/request/src','packages/lib','packages/gray-room/src','packages/llm/src','packages/server-utils/src','packages/server-config','packages/server/services','packages/features/src','packages/config'];
const R=[
[/from '\.\.\/\.\.\/utils\/logger\.js'/g,"from '@a2a/server-utils/logger'"],
[/from '\.\.\/utils\/logger\.js'/g,"from '@a2a/server-utils/logger'"],
[/from '\.\.\/\.\.\/\.\.\/utils\/logger\.js'/g,"from '@a2a/server-utils/logger'"],
[/from '\.\.\/\.\.\/\.\.\/\.\.\/utils\/logger\.js'/g,"from '@a2a/server-utils/logger'"],
[/from '\.\.\/\.\.\/utils\/ai-hub-url\.js'/g,"from '../../lib/ai-hub-url.js'"],
[/from '\.\.\/utils\/ai-hub-url\.js'/g,"from '../../../lib/ai-hub-url.js'"],
[/from '\.\.\/\.\.\/utils\/metrics\.js'/g,"from '../../lib/metrics.js'"],
[/from '\.\.\/utils\/metrics\.js'/g,"from '../../../lib/metrics.js'"],
[/from '\.\.\/\.\.\/utils\/mkdtemp-os-tmp\.js'/g,"from '../../lib/mkdtemp-os-tmp.js'"],
[/from '\.\.\/utils\/mkdtemp-os-tmp\.js'/g,"from '../../../lib/mkdtemp-os-tmp.js'"],
[/from '\.\.\/\.\.\/utils\/ai-hub-chat-sync\.js'/g,"from '../../lib/ai-hub-chat-sync.js'"],
[/from '\.\.\/utils\/ai-hub-chat-sync\.js'/g,"from '../../../lib/ai-hub-chat-sync.js'"],
[/from '\.\.\/\.\.\/utils\/deep-clone-json\.js'/g,"from '../../lib/deep-clone-json.js'"],
[/from '\.\.\/utils\/deep-clone-json\.js'/g,"from '../../../lib/deep-clone-json.js'"],
[/from '\.\.\/\.\.\/utils\/errors\.js'/g,"from '../../lib/errors.js'"],
[/from '\.\.\/utils\/errors\.js'/g,"from '../../../lib/errors.js'"],
[/from '\.\.\/\.\.\/utils\/crypto\.js'/g,"from '../../lib/crypto.js'"],
[/from '\.\.\/utils\/crypto\.js'/g,"from '../../../lib/crypto.js'"],
[/from '\.\.\/\.\.\/utils\/fs-access\.js'/g,"from '../../lib/fs-access.js'"],
[/from '\.\.\/utils\/fs-access\.js'/g,"from '../../../lib/fs-access.js'"],
[/from '\.\.\/\.\.\/request\/request\.service\.js'/g,"from '../../request/src/request.service.js'"],
[/from '\.\.\/request\/request\.service\.js'/g,"from '../../../request/src/request.service.js'"],
[/from '\.\.\/\.\.\/transform\/index\.js'/g,"from '../../transform/src/index.js'"],
[/from '\.\.\/transform\/index\.js'/g,"from '../../../transform/src/index.js'"],
[/from '\.\.\/\.\.\/transform\/types\.js'/g,"from '../../transform/src/types.js'"],
[/from '\.\.\/transform\/types\.js'/g,"from '../../../transform/src/types.js'"],
[/from '\.\.\/transform\/interrupt-trace-contract\.js'/g,"from '../../../transform/src/interrupt-trace-contract.js'"],
[/from '\.\.\/\.\.\/transform\/interrupt-trace-contract\.js'/g,"from '../../transform/src/interrupt-trace-contract.js'"],
[/from '\.\.\/\.\.\/daemon\/llm-hub-poll\.js'/g,"from '../../daemon/src/daemon/llm-hub-poll.js'"],
[/from '\.\.\/daemon\/llm-hub-poll\.js'/g,"from '../../../daemon/src/daemon/llm-hub-poll.js'"],
[/from '\.\.\/\.\.\/\.\.\/\.\.\/packages\/config\/index\.js'/g,"from '@a2a/config'"],
[/from '\.\.\/\.\.\/\.\.\/packages\/config\/index\.js'/g,"from '@a2a/config'"],
[/from '\.\.\/\.\.\/packages\/config\/index\.js'/g,"from '@a2a/config'"],
[/from '\.\.\/packages\/config\/index\.js'/g,"from '@a2a/config'"],
[/from '\.\.\/\.\.\/\.\.\/config\/router-static\.js'/g,"from '@a2a/config'"],
[/from '\.\.\/\.\.\/config\/router-static\.js'/g,"from '@a2a/config'"],
[/from '\.\.\/config\/router-static\.js'/g,"from '@a2a/config'"],
[/from '\.\.\/\.\.\/\.\.\/server-config\/index\.js'/g,"from '@a2a/config'"],
[/from '\.\.\/\.\.\/server-config\/index\.js'/g,"from '@a2a/config'"],
[/from '\.\.\/server-config\/index\.js'/g,"from '@a2a/config'"],
[/from '\.\.\/\.\.\/actions\/action-processor\.js'/g,"from '../../actions/src/action-processor.js'"],
[/from '\.\.\/actions\/action-processor\.js'/g,"from '../../../actions/src/action-processor.js'"],
[/from '\.\.\/\.\.\/actions\/action-registry\.js'/g,"from '../../actions/src/action-registry.js'"],
[/from '\.\.\/actions\/action-registry\.js'/g,"from '../../../actions/src/action-registry.js'"],
[/from '\.\.\/\.\.\/actions\/types\.js'/g,"from '../../actions/src/types.js'"],
[/from '\.\.\/actions\/types\.js'/g,"from '../../../actions/src/types.js'"],
[/from '\.\.\/\.\.\/actions\/handlers\/file-operations\.js'/g,"from '../../actions/src/handlers/file-operations.js'"],
[/from '\.\.\/actions\/handlers\/file-operations\.js'/g,"from '../../../actions/src/handlers/file-operations.js'"],
[/from '\.\.\/\.\.\/actions\/handlers\/mcp-call\.js'/g,"from '../../actions/src/handlers/mcp-call.js'"],
[/from '\.\.\/types\/index\.js'/g,"from '@a2a/server-protocol'"],
[/from '\.\.\/\.\.\/types\/index\.js'/g,"from '@a2a/server-protocol'"],
[/from '\.\.\/\.\.\/server\/src\/types\/index\.js'/g,"from '@a2a/server-protocol'"],
[/from '\.\.\/\.\.\/services\/src\/utils\/invoke\.service\.js'/g,"from '../../services/src/utils/invoke.service.js'"],
[/from '\.\.\/services\/utils\/invoke\.service\.js'/g,"from '../../services/src/utils/invoke.service.js'"],
[/from '\.\.\/\.\.\/services\/registry-v2\.js'/g,"from '../../services/src/registry-v2.js'"],
[/from '\.\.\/services\/registry-v2\.js'/g,"from '../../../services/src/registry-v2.js'"],
[/from '\.\.\/lib\/event-bus\.js'/g,"from '../../../lib/event-bus.js'"],
[/from '\.\.\/server\/src\/orchestrator-kernel\.js'/g,"from '../../../server/src/orchestrator-kernel.js'"],
[/from '\.\.\/services\/core\/request-processor\/request-processor\.service\.js'/g,"from '../request-processor/request-processor.service.js'"],
[/from '\.\.\/\.\.\/core\/transform\/index\.js'/g,"from '../../../../transform/src/index.js'"],
[/from '\.\.\/\.\.\/core\/transform\/types\.js'/g,"from '../../../../transform/src/types.js'"],
[/from '\.\.\/core\/transform\/index\.js'/g,"from '../../../transform/src/index.js'"],
[/from '\.\.\/core\/transform\/interrupt-trace-contract\.js'/g,"from '../../../transform/src/interrupt-trace-contract.js'"],
[/from '\.\.\/\.\.\/core\/transform\/interrupt-trace-contract\.js'/g,"from '../../../../transform/src/interrupt-trace-contract.js'"],
[/from '\.\.\/\.\.\/\.\.\/\.\.\/packages\/gray-room\/src\/core\/request-processor\/gray-room-orchestrator\.js'/g,"from '../../../../gray-room/src/core/request-processor/gray-room-orchestrator.js'"],
[/from '\.\.\/\.\.\/\.\.\/\.\.\/packages\/gray-room\/src\/core\/request-processor\/gray-room-trigger\.js'/g,"from '../../../../gray-room/src/core/request-processor/gray-room-trigger.js'"],
[/from '\.\.\/\.\.\/\.\.\/\.\.\/packages\/transform\/index\.js'/g,"from '../../../../transform/src/index.js'"],
[/@a2a\/lib\/logger/g,'@a2a/server-utils/logger'],
[/@a2a\/server-config\/index\.js/g,'@a2a/config'],
[/@a2a\/server-utils\/agent-utils/g,'@a2a/server-utils'],
];
let n=0;
for(const d of dirs){if(!existsSync(d))continue;for(const f of walk(d)){let c=readFileSync(f,'utf8');const o=c;for(const[p,r]of R)c=c.replace(p,r);if(c!==o){writeFileSync(f,c);n++;console.log('F:'+basename(f));}}}
console.log('Fixed:'+n);
