<?php

namespace App\Http\Controllers\Backend\Helpers;

use App\Helpers\ArrayHelper;
use App\Helpers\FileHelper;
use App\Helpers\JsonHelper;
use App\Helpers\LogHelper;
use App\Helpers\PathHelper;
use App\Helpers\StringHelper;
use App\Hooks\FileFacade;
use InvalidArgumentException;

class CssProcessor
{
    protected JsonHelper $jsonHelper;

    public function __construct()
    {
        $this->jsonHelper = new JsonHelper();
    }

    /**
     * Process CSS definitions for specified modules.
     *
     * @param array $moduleNames List of module names to process.
     * @return array Log messages.
     * @throws InvalidArgumentException
     */
    public function processAllModules(array $moduleNames): array
    {
        $log = [];
        $installerBaseDir = PathHelper::join(base_path('install-modules'), 'aiInstaller');
        $outputBaseDir = PathHelper::join(storage_path('ai/system'), 'css');
        $manifestContent = "// Auto-generated by Installer\n";
        $manifestPath = PathHelper::join($outputBaseDir, 'modules-imports.scss');

        // Validate paths
        if (!PathHelper::isValid($installerBaseDir) || !PathHelper::isValid($outputBaseDir)) {
            throw new InvalidArgumentException('Invalid installer or output directory path');
        }

        try {
            // Create output directory if it doesn't exist
            if (!FileHelper::isAccessible($outputBaseDir)) {
                FileHelper::createDirectory($outputBaseDir, 0777, true);
                $log[] = "Created CSS output directory: {$outputBaseDir}";
            }

            foreach ($moduleNames as $moduleName) {
                $moduleLog = $this->processModuleCss($moduleName, $installerBaseDir, $outputBaseDir);
                $log = array_merge($log, $moduleLog);

                // Check if CSS was generated for this module
                $cssGenerated = ArrayHelper::any($moduleLog, function ($logEntry) use ($moduleName) {
                    return StringHelper::contains($logEntry, "Generated CSS for module {$moduleName}");
                });

                if ($cssGenerated) {
                    $relativePath = './' . $moduleName . '.css';
                    $manifestContent .= "@import '" . $relativePath . "';\n";
                }
            }

            // Save manifest file
            FileHelper::write($manifestPath, $manifestContent);
            $log[] = "Generated CSS import manifest: {$manifestPath}";

            LogHelper::debug('CssProcessor::processAllModules', 'Successfully processed CSS for all modules', [
                'modulesCount' => count($moduleNames)
            ]);

            return $log;

        } catch (\Exception $e) {
            LogHelper::error('CssProcessor::processAllModules', 'Failed to process CSS for modules', [
                'error' => $e->getMessage()
            ]);
            throw $e;
        }
    }

    /**
     * Process CSS for a single module by reading definitions from the installer source.
     *
     * @param string $moduleName
     * @param string $installerBaseDir Path to install-modules/aiInstaller
     * @param string $outputBaseDir Path to storage/ai/system/css
     * @return array Log messages for this module.
     * @throws InvalidArgumentException
     */
    protected function processModuleCss(string $moduleName, string $installerBaseDir, string $outputBaseDir): array
    {
        $log = [];
        $moduleInstallerPath = PathHelper::join($installerBaseDir, $moduleName);
        $cssConfigPath = PathHelper::join($moduleInstallerPath, '_i', 'css.json');
        $finalCssContent = "";

        // Validate paths
        if (!PathHelper::isValid($moduleInstallerPath) || !PathHelper::isValid($cssConfigPath)) {
            throw new InvalidArgumentException('Invalid module or CSS config path');
        }

        try {
            // Check if CSS config exists
            if (!FileHelper::isAccessible($cssConfigPath)) {
                return [];
            }

            // Read and decode CSS config
            $cssConfig = JsonHelper::decode(FileHelper::read($cssConfigPath));
            if (!ArrayHelper::isAssociative($cssConfig)) {
                $log[] = "Warning: Invalid or empty css.json for module {$moduleName}.";
                return $log;
            }

            // Process each CSS JSON file
            foreach ($cssConfig as $cssJsonFile) {
                $cssJsonPath = PathHelper::join($moduleInstallerPath, StringHelper::trim($cssJsonFile, '/'));
                
                if (FileHelper::isAccessible($cssJsonPath)) {
                    $jsonData = JsonHelper::decode(FileHelper::read($cssJsonPath));
                    if (ArrayHelper::isAssociative($jsonData)) {
                        $finalCssContent .= $this->jsonToCss($jsonData) . "\n\n";
                    } else {
                        $log[] = "Warning: Invalid JSON in {$cssJsonFile} for module {$moduleName}.";
                    }
                } else {
                    $log[] = "Warning: CSS JSON file not found: {$cssJsonFile} in installer source for module {$moduleName}.";
                }
            }

            // Save generated CSS if not empty
            if (!StringHelper::isEmpty(trim($finalCssContent))) {
                $outputCssPath = PathHelper::join($outputBaseDir, $moduleName . '.css');
                FileHelper::write($outputCssPath, $finalCssContent);
                $log[] = "Generated CSS for module {$moduleName} at {$outputCssPath}.";
            } else {
                $log[] = "No CSS content generated for module {$moduleName} (check css.json references).";
            }

            return $log;

        } catch (\Exception $e) {
            LogHelper::error('CssProcessor::processModuleCss', 'Failed to process CSS for module', [
                'module' => $moduleName,
                'error' => $e->getMessage()
            ]);
            throw $e;
        }
    }

    /**
     * Convert JSON data structure to CSS string.
     *
     * @param array $json
     * @param int $indentLevel
     * @return string
     */
    protected function jsonToCss(array $json, int $indentLevel = 0): string
    {
        $css = '';
        $indent = str_repeat('  ', $indentLevel);

        foreach ($json as $selector => $styles) {
            if (ArrayHelper::isAssociative($styles)) {
                $css .= $indent . $selector . " {\n";
                $css .= $this->jsonToCss($styles, $indentLevel + 1);
                $css .= $indent . "}\n\n";
            } else {
                $escapedStyles = StringHelper::escapeCss((string)$styles);
                $css .= $indent . $selector . ": " . $escapedStyles . ";\n";
            }
        }

        return $css;
    }

    /**
     * Get file content from installer directory.
     *
     * @param string $path
     * @param string $moduleName
     * @return string|null
     */
    private function getFile(string $path, string $moduleName = ''): ?string
    {
        $installerBaseDir = PathHelper::join(base_path('install-modules'), 'aiInstaller');
        $fullPath = PathHelper::join($installerBaseDir, $moduleName, $path);

        if (FileHelper::isAccessible($fullPath)) {
            return FileHelper::read($fullPath);
        }

        return null;
    }
}
