packages:
  - 'packages/server'
  - 'packages/actions'
  - 'packages/server-ai'
  - 'packages/gray-room'
  - 'packages/server-config'
  - 'packages/server-protocol'
  - 'packages/server-utils'
  - 'packages/daemon'
  - 'packages/request'
  - 'packages/features'
  - 'packages/services'
