#!/usr/bin/env node

const fs = require('fs').promises;
const path = require('path');

/**
 * Task Manager for Documentation Updates
 * 
 * This script manages the execution of tasks generated by task-generator.js.
 * It uses the existing documentation management system to execute tasks.
 */

class TaskManager {
    constructor() {
        this.tasksDir = '.clinerules/tasks';
        this.documentationManager = null;
    }

    async initialize() {
        try {
            // Load documentation manager
            const DocumentationManager = require('./documentation-manager.js');
            this.documentationManager = new DocumentationManager();

            console.log('✅ Task Manager initialized');
            return true;
        } catch (error) {
            console.error('❌ Task Manager initialization failed:', error.message);
            return false;
        }
    }

    /**
     * List all tasks
     */
    async listTasks() {
        try {
            const files = await fs.readdir(this.tasksDir);
            const taskFiles = files.filter(file => file.endsWith('.json'));
            
            const tasks = [];
            for (const file of taskFiles) {
                const filePath = path.join(this.tasksDir, file);
                const content = await fs.readFile(filePath, 'utf8');
                tasks.push(JSON.parse(content));
            }

            return tasks.sort((a, b) => {
                const priorityOrder = { high: 3, medium: 2, low: 1 };
                return priorityOrder[b.priority] - priorityOrder[a.priority];
            });
        } catch (error) {
            console.error('❌ Error listing tasks:', error.message);
            return [];
        }
    }

    /**
     * Execute a specific task
     */
    async executeTask(taskId) {
        try {
            const taskFile = path.join(this.tasksDir, `${taskId}.json`);
            const content = await fs.readFile(taskFile, 'utf8');
            const task = JSON.parse(content);

            if (task.status !== 'pending') {
                console.log(`❌ Task ${taskId} is not pending (status: ${task.status})`);
                return false;
            }

            console.log(`🚀 Executing task ${taskId}: ${task.document_path}`);

            // Update task status to in_progress
            task.status = 'in_progress';
            task.started_at = new Date().toISOString();
            await fs.writeFile(taskFile, JSON.stringify(task, null, 2));

            // Execute the task based on type
            let result;
            if (task.type === 'document_update') {
                result = await this.executeUpdateTask(task);
            } else if (task.type === 'document_create') {
                result = await this.executeCreateTask(task);
            } else {
                throw new Error(`Unknown task type: ${task.type}`);
            }

            // Update task status
            task.status = result.success ? 'completed' : 'failed';
            task.completed_at = new Date().toISOString();
            task.results = result.results || [result.message];

            await fs.writeFile(taskFile, JSON.stringify(task, null, 2));

            const status = result.success ? '✅' : '❌';
            console.log(`${status} Task ${taskId} ${task.status}: ${result.message}`);

            return result.success;
        } catch (error) {
            console.error(`❌ Failed to execute task ${taskId}:`, error.message);
            
            // Mark task as failed
            try {
                const taskFile = path.join(this.tasksDir, `${taskId}.json`);
                const content = await fs.readFile(taskFile, 'utf8');
                const task = JSON.parse(content);
                
                task.status = 'failed';
                task.completed_at = new Date().toISOString();
                task.results = [error.message];
                
                await fs.writeFile(taskFile, JSON.stringify(task, null, 2));
            } catch (updateError) {
                console.error('❌ Failed to update task status:', updateError.message);
            }

            return false;
        }
    }

    /**
     * Execute update task
     */
    async executeUpdateTask(task) {
        try {
            // Use the existing documentation manager to handle updates
            const result = await this.documentationManager.handleDocumentationUpdate(
                task.document_path,
                'outdated',
                null
            );

            if (result.success) {
                return {
                    success: true,
                    message: `Document ${task.document_path} marked as outdated and new version created`,
                    results: [`New version: ${result.newDocumentPath}`, `Review request: ${result.reviewRequest.id}`]
                };
            } else {
                return {
                    success: false,
                    message: result.error,
                    results: [result.error]
                };
            }
        } catch (error) {
            return {
                success: false,
                message: `Failed to update document: ${error.message}`,
                results: [error.message]
            };
        }
    }

    /**
     * Execute create task
     */
    async executeCreateTask(task) {
        try {
            // Generate content based on task description
            const content = this.generateContent(task.description, task.document_path);

            // Use the existing documentation manager to create new document
            const result = await this.documentationManager.handleDocumentationUpdate(
                task.document_path,
                'new',
                content
            );

            if (result.success) {
                return {
                    success: true,
                    message: `Document ${task.document_path} created successfully`,
                    results: [`Created: ${result.newDocumentPath}`, `Review request: ${result.reviewRequest.id}`]
                };
            } else {
                return {
                    success: false,
                    message: result.error,
                    results: [result.error]
                };
            }
        } catch (error) {
            return {
                success: false,
                message: `Failed to create document: ${error.message}`,
                results: [error.message]
            };
        }
    }

    /**
     * Generate content for new documents
     */
    generateContent(description, documentPath) {
        const contentTemplates = {
            'ARCHITECTURE.md': `# System Architecture

## Overview
${description}

## Components

### Core Components
- Component 1
- Component 2
- Component 3

### Data Flow
1. Step 1
2. Step 2
3. Step 3

## Integration Points
- External systems
- APIs
- Databases

Generated at: ${new Date().toISOString()}
`
        };

        const basename = path.basename(documentPath);
        return contentTemplates[basename] || `# ${basename}

${description}

Generated at: ${new Date().toISOString()}
`;
    }

    /**
     * Execute all pending tasks
     */
    async executeAllTasks() {
        const tasks = await this.listTasks();
        const pendingTasks = tasks.filter(task => task.status === 'pending');

        if (pendingTasks.length === 0) {
            console.log('✅ No pending tasks found');
            return true;
        }

        console.log(`🚀 Executing ${pendingTasks.length} pending tasks...`);

        let successCount = 0;
        let failureCount = 0;

        for (const task of pendingTasks) {
            const success = await this.executeTask(task.id);
            if (success) {
                successCount++;
            } else {
                failureCount++;
            }
        }

        console.log(`\n📊 Execution Summary:`);
        console.log(`✅ Successful: ${successCount}`);
        console.log(`❌ Failed: ${failureCount}`);
        console.log(`📈 Success Rate: ${((successCount / pendingTasks.length) * 100).toFixed(1)}%`);

        return failureCount === 0;
    }

    /**
     * Get task statistics
     */
    async getTaskStats() {
        const tasks = await this.listTasks();
        
        const stats = {
            total: tasks.length,
            pending: tasks.filter(t => t.status === 'pending').length,
            in_progress: tasks.filter(t => t.status === 'in_progress').length,
            completed: tasks.filter(t => t.status === 'completed').length,
            failed: tasks.filter(t => t.status === 'failed').length,
            by_priority: {
                high: tasks.filter(t => t.priority === 'high').length,
                medium: tasks.filter(t => t.priority === 'medium').length,
                low: tasks.filter(t => t.priority === 'low').length
            },
            by_type: {
                document_update: tasks.filter(t => t.type === 'document_update').length,
                document_create: tasks.filter(t => t.type === 'document_create').length
            }
        };

        return stats;
    }

    /**
     * Generate execution report
     */
    async generateReport() {
        const tasks = await this.listTasks();
        const stats = await this.getTaskStats();

        const report = {
            timestamp: new Date().toISOString(),
            summary: stats,
            tasks: tasks.map(task => ({
                id: task.id,
                type: task.type,
                priority: task.priority,
                status: task.status,
                document_path: task.document_path,
                reason: task.reason || task.description,
                created_at: task.created_at,
                started_at: task.started_at,
                completed_at: task.completed_at,
                results: task.results
            }))
        };

        return report;
    }
}

// CLI interface
if (require.main === module) {
    const manager = new TaskManager();

    const args = process.argv.slice(2);
    const command = args[0];

    if (!command) {
        console.log('Usage: node task-manager.js <command> [options]');
        console.log('Commands:');
        console.log('  list                           List all tasks');
        console.log('  execute <task-id>              Execute specific task');
        console.log('  execute-all                    Execute all pending tasks');
        console.log('  stats                          Show task statistics');
        console.log('  report                         Generate execution report');
        process.exit(1);
    }

    manager.initialize().then(async () => {
        switch (command) {
            case 'list':
                const tasks = await manager.listTasks();
                console.log('📋 All Tasks:');
                tasks.forEach(task => {
                    console.log(`  ${task.id}: ${task.document_path} (${task.priority}) - ${task.status}`);
                });
                break;

            case 'execute':
                const taskId = args[1];
                if (!taskId) {
                    console.log('Usage: node task-manager.js execute <task-id>');
                    process.exit(1);
                }
                await manager.executeTask(taskId);
                break;

            case 'execute-all':
                await manager.executeAllTasks();
                break;

            case 'stats':
                const stats = await manager.getTaskStats();
                console.log('📊 Task Statistics:');
                console.log(JSON.stringify(stats, null, 2));
                break;

            case 'report':
                const report = await manager.generateReport();
                console.log('📋 Task Execution Report:');
                console.log(JSON.stringify(report, null, 2));
                break;

            default:
                console.log('Unknown command:', command);
        }
    });
}

module.exports = TaskManager;